spring.application.name=order-service

spring.datasource.url=jdbc:mysql://localhost:3306/orders_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.pattern.level=%5p [${spring.application.name:},%X{correlationId}]
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

spring.security.oauth2.resourceserver.jwt.secret-key=my-secret-key-my-secret-key-my-secret-key